#!/usr/bin/env bash
# This script parses the Apache log file and displays the visitor IP along with the HTTP status code.

if [ ! -f apache-access.log ]; then
	echo 'Apach log file "apache-access.log" not found.'
	exit 1
fi

awk '{print $1, $9}' apache-access.log