#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code and displays the data.

if [ ! -f apache-access.log ]; then
	echo 'Apache log file "apache-access.log" not found.'
	exit 1
fi
awk '{count[$1 " " $9]++} END {for (i in count) print count[i], i}' apache-access.log | sort -nr